package research.sg.edu.edapp.FinalClasses;

import java.util.Arrays;
import java.util.List;

/**
 * Created by weirdmyth on 26/11/16.
 */

public final class AppCategory {
    public static List<String> email = Arrays.asList("com.google.android.gm",
            "com.google.android.gms.ui",
            "com.google.android.apps.inbox",
            "com.google.android.gms",
            "com.android.email",
            "com.microsoft.office.outlook"
    );

    public static List<String> entertainment= Arrays.asList("com.chess",
            "com.pft.starsports.ui",
            "com.google.android.youtube",
            "gridviewexample.javatechig.packagecom.emplayer",
            "com.sec.android.gallery3d",
            "com.saavn.android",
            "com.bsbportal.music",
            "com.sonyliv",
            "in.startv.hotstar",
            "com.tv.v18.viola",
            "com.jio.jioplay.tv",
            "com.viacom18.colorstv",
            "com.google.android.youtube",
            "com.jio.media.ondemand",
            "com.musixmatch.android.lyrify",
            "com.gaana",
            "com.jio.media.jiobeats"

            );

    public static List<String> im=Arrays.asList("com.whatsapp",
            "com.freelancer.android.messenger",
            "com.google.android.talk",
            "com.skype.raider",
            "com.android.mms",
            "com.android.messaging",
            "com.google.android.apps.messaging",
            "com.asus.message",
            "com.bsb.hike",
            "com.imo.android.imoim",
            "org.telegram.messenger",
            "com.tencent.mm",
            "com.gbwhatsapp",
            "com.gbwhatsapp3",
            "jp.naver.line.android",
            "com.facebook.orca",
            "com.viber.voip"
    );

    public static List<String> social=Arrays.asList("com.android.contacts",
            "com.android.dialer",
            "com.android.phone",
            "com.asus.contacts",
            "com.truecaller",
            "com.trulymadly.android.app",
            "com.facebook.katana",
            "com.quora.android",
            "com.linkedin.android",
            "com.meetup",
            "com.instagram.android"
    );

    public static List<String> surfing=Arrays.asList("com.android.chrome",
            "com.google.android.googlequicksearchbox",
            "com.android.browser",
            "org.mozilla.firefox",
            "com.google.android.googlequicksearchbox:search",
            "com.opera.mini.android",
            "net.one97.paytm",
            "in.goindigo.android",
            "com.olr.rechargeitnow",
            "com.paytm.paywith",
            "in.amazon.mShop.android.shopping",
            "com.mobikwik_new",
            "com.mobile.indiapp",
            "com.tripadvisor.tripadvisor",
            "com.goibibo",
            "com.makemytrip",
            "com.olacabs.customer",
            "com.flipkart.android",
            "com.snapdeal.main",

            "com.sbi.SBAnywhere.Hindi",
            "com.sbi.sbiquick",
            "com.ge.capital.konysbiapp",
            "com.sbi.erupee",
            "com.freedomrewardz",
            "com.sbi.SBAnywhereSaral",
            "com.sbi.mCash",
            "com.sbi.SBAssociate",
            "com.sbi.upi",
            "com.sbi.noqueue",
            "com.sbi.SBIFreedomPlus",
            "com.sbi.SBFreedom",
            "com.infosys.android.ui",
            "com.sangamone.apnakhatapnb",
            "com.pnbrewardz",
            "com.msf.kbank.mobile",
            "src.com.idbi",
            "com.fss.bob",
            "com.fss.abk",
            "com.fss.ubipsp",
            "com.paymate.syndicatebank",
            "src.com.infosys.boi",
            "com.vayana.mtc.corpbank",
            "com.atomyes",
            "com.fss.alb",
            "com.fss.vijaya",
            "com.axis.mobile",
            "com.csam.icici.bank.imobile",
            "com.snapwork.hdfc"

            );

    /*public static List<String> misc= Arrays.asList("android.process.acore",
            "com.android.vending",
            "com.android.settings",
            "com.test.a.sample.tapsense",
            "com.android.launcher",
            "android",
            "com.sec.android.app.launcher",
            "com.android.systemui",
            "com.lenovo.ideafriend",
            "Dummy_Pkg",
            "com.lenovo.xlauncher",
            "com.asus.launcher",
            "com.kokteyl.goal",
            "com.android.stk",
            "com.company.MyESS"
    );

    public static List<String> utility=Arrays.asList("com.traber.blueappsender",
            "com.google.android.apps.docs",
            "com.google.android.apps.docs.editors.sheets",
            "com.rhmsoft.fm",
            "research.sg.edu.edapp",
            "com.aed.droidvpn",
            "edu.umich.PowerTutor",
            "com.google.android.apps.books",
            "LockScreen",
            "com.example.android.softkeyboard",
            "dpp.tnpsubscribe",
            "com.google.android.calendar",
            "com.focusatwill.androidApp",
            "com.duolingo",
            "com.ixigo.train.ixitrain",
            "com.sasyabook.runningtrainstatus",
            "com.google.android.apps.maps",
            "com.strava",
            "com.android.documentsui",
            "com.estrongs.android.pop",
            "com.stumbleupon.android.app",
            "com.vishy.mypnralerts",
            "com.bt.bms",
            "com.teamviewer.teamviewer.market.mobile",
            "com.socialnmobile.dictapps.notepad.color.note",
            "com.imo.android.imoim",
            "com.google.android.gsf.login",
            "com.sec.android.app.myfiles",
            "com.sec.android.app.clockpackage",
            "com.UCMobile.intl",
            "it.nikodroid.offline",
            "com.httrack.android",
            "com.dictionary.bn",
            "com.android.providers.calendar",
            "com.amazon.kindle","org.sandroproxy.drony",
            "com.surfeasy",
            "com.android.vpndialogs",
            "com.wordwebsoftware.android.wordweb",
            "com.microsoft.office.word",
            "com.android.calculator2",
            "com.google.android.keep","com.ksmobile.cb",
            "com.asus.filemanager"
            );*/

    /*public static List<String> banking= Arrays.asList("com.sbi.SBAnywhere.Hindi",
            "com.sbi.sbiquick",
            "com.ge.capital.konysbiapp",
            "com.sbi.erupee",
            "com.freedomrewardz",
            "com.sbi.SBAnywhereSaral",
            "com.sbi.mCash",
            "com.sbi.SBAssociate",
            "com.sbi.upi",
            "com.sbi.noqueue",
            "com.sbi.SBIFreedomPlus",
            "com.sbi.SBFreedom",
            "com.infosys.android.ui",
            "com.sangamone.apnakhatapnb",
            "com.pnbrewardz",
            "com.msf.kbank.mobile",
            "src.com.idbi",
            "com.fss.bob",
            "com.fss.abk",
            "com.fss.ubipsp",
            "com.paymate.syndicatebank",
            "src.com.infosys.boi",
            "com.vayana.mtc.corpbank",
            "com.atomyes",
            "com.fss.alb",
            "com.fss.vijaya",
            "com.axis.mobile",
            "com.csam.icici.bank.imobile",
            "com.snapwork.hdfc"
    );*/
}
